app/users/models.py
from app import db


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(20))

    def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

    def __repr__(self):
        return '<User %r>' % (self.name)


class Feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer, primary_key=True)
    rating = db.Column(db.Integer)
    comment = db.Column(db.String(50))
    user_name = db.Column(db.String(50), db.ForeignKey("user.name"))
    rater_name = db.Column(db.String(50), db.ForeignKey("user.name"))

    user = db.relationship("User", backref="feedback",
                           foreign_keys=[user_name])

    rater = db.relationship("User", backref="feedback_given",
                            foreign_keys=[rater_name])

    def __init__(self, rating, rater, user, comment=None):
        self.comment = comment
        self.rating = rating
        self.rater_name = rater.name
        self.user_name = user.name


class Notification(db.Model):
    __tablename__ = 'notification'
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(50))

    user_name = db.Column(db.String(50), db.ForeignKey("user.name"))
    user = db.relationship("User", backref="notifications",
                           foreign_keys=[user_name])

    def __init__(self, description, user):
        self.user_name = user.name
        self.description = description

class Route(db.Model):
    __tablename__ = 'route'
    id = db.Column(db.Integer, primary_key=True)
    address = db.Column(db.String(50))

    user_name = db.Column(db.String(50), db.ForeignKey("user.name"))
    user = db.relationship("User", backref="routes", foreign_keys=[user_name])

    def __init__(self, address, user):
    	self.user_name = user.name
	self.address = address

app/forms.py
from flask.ext.wtf import Form, TextField, PasswordField, BooleanField, SelectField, SelectMultipleField
from flask.ext.wtf import Required, Email

class AddUser(Form):
    user = TextField('user', [Required()])
    password = PasswordField('password', [Required()])
    confirm_pass = PasswordField('confirm_pass', [Required()])
    email = TextField('email', [Required(), Email()])

class LeaveFeedback(Form):
    comment = TextField('comment')
    rating = TextField('rating', [Required()])

app/__init__.py
from flask import Flask, g, session
from flask.ext.sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
db.init_app(app)


@app.before_request
def before_request():
    g.db = db
    g.app = app
    g.user = None
    session['username'] = 'TestName'

# Blueprints
from app.users.views import mod as usersModule
app.register_blueprint(usersModule)

from app.views import mod as appModule
app.register_blueprint(appModule)

# Later on you'll import the other blueprints the same way:
#from app.comments.views import mod as commentsModule
#from app.posts.views import mod as postsModule
#app.register_blueprint(commentsModule)
#app.register_blueprint(postsModule)

app/users/views.py
from flask import Blueprint, render_template, g, request

from app.users.models import User, Feedback, Notification, Route
from app.forms import LeaveFeedback
from app import db

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.before_request
def before_request():
    g.user = User.query.filter_by(name='TestName').first()


@mod.route('/me/')
def home():
    form = LeaveFeedback()

    feedback = g.user.feedback
    return render_template("profile.html", form=form, user=g.user, person=g.user, feedback=feedback)


@mod.route('/<user_name>/notifications/', methods=['GET'])
def notifications(user_name):
    notifications = Notification.query.filter_by(user_name=user_name).all()
    all_notifications = Notification.query.all()
    print [notification.user_name for notification in all_notifications]
    if not notifications:
        notifications = "No notifications"
    return render_template('notifications.html', user=g.user,
                           notifications=notifications)

@mod.route('/<user_id>', methods=['GET','POST'])
def view_profile(user_id):

    person = User.query.filter_by(name=user_id).first()

    if person:
        if request.method == "POST":
            db.session.add(Feedback(user=person, rater=g.user, comment=form.comment.data, rating=int(form.rating.data)))
            db.session.commit()

        feedback = Feedback.query.filter_by(user_name=person.name).all()
        return render_template("profile.html",form=form, user=g.user, person=person, feedback=feedback)
    return "Profile not found."

@mod.route('/<user_name>/routes/', methods=['GET'])
def routes(user_name):
    routes = Route.query.filter_by(user_name=user_name).all()
    all_routes = Route.query.all()
    print [route.user_name for route in all_routes]
    if not routes:
        routes = "No routes"
    return render_template('routes.html', user=g.user,
                           routes=routes)

app/views.py
from flask import g, render_template, Blueprint, request
from forms import AddUser
from users.models import User
from app import db

mod = Blueprint('app', __name__)


@mod.before_request
def before_request():
    g.user = User.query.filter_by(name='TestName').first()


@mod.route('/', methods=['GET'])
def root():
    return render_template('index.html')


@mod.route('/route', methods=['GET', 'POST'])
def route():
    return render_template('routes.html', user=g.user)

@mod.route('/matching/', methods=['get', 'post'])
def matching():
    return render_template('map.html')

@mod.route("/add_user", methods=['GET', 'POST'])
def register():
    #user = current_user
    form = AddUser()
    message = ""

    if request.method == "POST":
        if form.password.data != form.confirm_pass.data:
            message="The passwords provided did not match!\n"
        else:
            #Add user to db
            db.session.add(User(name=form.user.data,
                email = form.email.data, password=form.password.data))
            db.session.commit()
            message = form.user.data+" has been added successfully!\n"

    return render_template('add_user.html', form=form, message=message)

app/templates/add_user.html
{% extends 'base.html' %}

{% block content %}
    <form action="/add_user" method="POST">
        Username: {{form.user}}</br>
        Password: {{form.password}}</br>
        Confirm Password: {{form.confirm_pass}}</br>
        Email: {{form.email}}</br>
        <input type="submit" value="Add User"></input></br>
    </form>
    {% if message %}
        {{message}}
    {% endif %}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Rideshare{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link rel="stylesheet" href="{{ url_for("static", filename="css/bootstrap.css") }}" />
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link rel="stylesheet" href="{{ url_for("static", filename="css/bootstrap-responsive.css") }}" />
    <script src="{{ url_for("static", filename="js/jquery.js") }}"></script>
    {% block head %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{{ url_for("app.root") }}">Rideshare</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            {% if session.username %}
              Logged in as <a href="{{ url_for("users.home") }}" class="navbar-link">{{session.username}}</a>
            {% else %}
              Logged in as <a href="/#" class="navbar-link">Guest</a>
            {% endif %}
            </p>
            <ul class="nav">
              <li><a href="{{ url_for("app.matching") }}">Match Making</a></li>
              <li><a href="{{ url_for("users.notifications", user_name=session.username) }}" class="navbar-link">Notifications</a></li>
            </ul>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li class="active"><a href="{{url_for("users.routes", user_name=session.username)}}">Route</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="nav-header">Sidebar</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="container content">
            {% block content %}{% endblock %}
          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <script src="{{ url_for("static", filename="js/bootstrap.min.js") }}"></script>

    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    Hello World!
{% endblock %}

app/templates/map.html
{% extends "base.html" %}
{% block title %}Route Planning{% endblock %}
{% block head %}
<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=AIzaSyBXFuYqnvdzyzfn2RcxQT-NptcT1qsR2Ks&sensor=false" type="text/javascript"></script>
<script type="text/javascript">

  var map = null;
  var geocoder = null;
	var directions = null;
	var isCreateHeadPoint = null;
	var headMarker, tailMarker;

    function initialize() {
      if (GBrowserIsCompatible()) {
        map = new GMap2(document.getElementById("map_canvas"));
        geocoder = new GClientGeocoder();
		map.setCenter(new GLatLng(44.58530, -123.252370), 13);
		directions = new GDirections(map);
		isCreateHeadPoint = true;
      }
    }

    function showAddress(address, flag) {
      if (geocoder) {
        geocoder.getLatLng(
          address,
          function(point) {
            if (!point) {
              alert(address + " not found");
            } else {
              if(flag){
				map.setCenter(point, 13);
				//var marker = new GMarker(point);
				headMarker = new GMarker(point);
				map.addOverlay(headMarker);

				// As this is user-generated content, we display it as
				// text rather than HTML to reduce XSS vulnerabilities.
				// marker.openInfoWindow(document.createTextNode(address));
			  } else {
				map.setCenter(point, 13);
				//var marker = new GMarker(point);
				tailMarker = new GMarker(point);
				map.addOverlay(tailMarker);

				// As this is user-generated content, we display it as
				// text rather than HTML to reduce XSS vulnerabilities.
				// marker.openInfoWindow(document.createTextNode(address));
			  }
            }
          }
        );
      }
    }

	function do_directions(){
		directions.load("from:" + headMarker.getPoint().lat()+ ", " +
                         headMarker.getPoint().lng() +
                         " to:" + tailMarker.getPoint().lat() + "," +
                         tailMarker.getPoint().lng(),
                         { getPolyline: true, getSteps: true });
	}

  $(document).ready(function() { initialize(); });
  $(window).unload( function(){ GUnload(); } )
</script>
{% endblock %}
{% block content %}
<form action="#" onsubmit="showAddress(this.source.value, true); return false">
  <p>Departure:
    <input type="text" size="60" name="source" value="" />
    <input type="submit" value="Add" />
  </p>
</form>

<form action="#" onsubmit="showAddress(this.destination.value, false); return false">
  <p>Destination:
    <input type="text" size="60" name="destination" value="" />
    <input type="submit" value="Add" />
  </p>
  <div id="map_canvas" style="width: 500px; height: 300px"></div>
</form>

<form action="#" onsubmit="do_directions(); return false">
    <p>
      <input type="submit" value="Get Directions!" />
    </p>
</form>

<form action="#" onsubmit="initialize(); return false">
    <p>
      <input type="submit" value="Reset" />
    </p>
</form>
{% endblock %}

app/templates/notifications.html
{% extends "base.html" %}

{% block content %}
<h1>Notifications</h1>
<table class="table">
<tr>
    <th>Description</th>
    <th>User</th>
</tr>
{% for notification in notifications %}
    <tr>
        <td>{{notification.description}}</td>
        <td><a href="/users/{{notification.user_name}}">{{notification.user_name}}</a></td>
    </tr>
{% endfor %}
</table>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
<!--
This should be replaced with a proper profile page, but we will use this until it is on the repo!
-->

{% block content %}
    {% if user != person %}
    <h1>{{person.name}}</h1>
    </br></br>
    {% endif %}
    {% include "profile_feedback.html" %}
{% endblock %}

app/templates/profile_feedback.html
<h2>Feedback</h2>
<form method="POST">
<table class="table">
<tr>
    <th>Rater</th>
    <th>Comment<th>
    <th>Rating (1-10)</th>
</tr>
{% for feed in feedback %}
    <tr>
        <td><a href="/users/{{feed.rater_name}}">{{feed.rater_name}}</a></td>
        <td>{{feed.comment}}</td>
        <td>{{feed.rating}}</td>
    </tr>
{% endfor %}
    {% if user != person %}
    <tr>
        <td>{{user.name}}</td>
        <td>{{form.comment}}</td>
        <td>{{form.rating}}</td>
    </tr>
    {% endif %}
</table>
<input type="submit" value="Leave Feedback"></input>
</form>

app/templates/routes.html
{% extends "base.html" %}

{% block content %}
<h1>Routes</h1>
<table class="table">
<tr>
    <th>Address</th>
    <th>User</th>
</tr>


<tr>
    <td>Route 1</td>
    <td>TestUser</td>
<tr>
    <td>Route 2</td>
    <td>TestUser</td>
</tr>
<tr>
    <td>Route 3</td>
    <td>TestUser</td>
</tr>

</table>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
{{ user.name }}<br>
{{ user.email }}<br>
{% endblock %}